CREATE TABLE MANAGER
(
  MANAGERNO NUMBER(10),
   ID VARCHAR2(30),
   PASSWD VARCHAR2(200 BYTE),
   MNAME VARCHAR2(20),
   PHONE VARCHAR2(14),
   GRADE NUMBER(3),
   REG_DATE DATE
)


CREATE SEQUENCE manager_seq
  START WITH 1 -- 시작 번호
  INCREMENT BY 1 -- 증가값
  MAXVALUE 9999999999 -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;


COMMENT ON TABLE MANAGER is '관리자';
COMMENT ON COLUMN MANAGER.managerno is '관리자번호';
COMMENT ON COLUMN MANAGER.id is '아이디';
COMMENT ON COLUMN MANAGER.passwd is '패스워드';
COMMENT ON COLUMN MANAGER.mname is '성명';
COMMENT ON COLUMN MANAGER.phone is '전화번호';
COMMENT ON COLUMN MANAGER.grade is '등급';
COMMENT ON COLUMN MANAGER.reg_date is '등록일자';
